### PR TITLE
Updating Rust Toolchain

### PR DESCRIPTION
**Pull request by xcthulhu**
Updating rust-toolchain to use nightly-2023-08-19

### CODE REVIEW

**Review by obsessed-cake — APPROVED** [review]

**Comment by obsessed-cake** [comment]
LGTM

**Comment by akorchyn** [comment]
Does a node work with new toolchain ?

**Comment by akorchyn** [comment]
https://github.com/paritytech/substrate/issues/13636

**Review by akorchyn — CHANGES_REQUESTED** [review]
we should test it first

**Comment by obsessed-cake** [comment]
```
$ cargo run -- --dev
     Finished dev [unoptimized + debuginfo] target(s) in 0.91s
     Running `target/debug/ggxchain-node --dev`
2023-08-20 20:29:40 GGX chain node    
2023-08-20 20:29:40 ✌️  version 0.1.0-54b64a0d5ec    
2023-08-20 20:29:40 ❤️  by GGXChain <admin@ggxchain.io>, 2021-2023    
2023-08-20 20:29:40 📋 Chain specification: Development    
2023-08-20 20:29:40 🏷  Node name: neat-bike-9362    
2023-08-20 20:29:40 👤 Role: AUTHORITY    
2023-08-20 20:29:40 💾 Database: RocksDb at /tmp/substratewc8gIL/chains/dev/db/full    
2023-08-20 20:29:40 ⛓  Native runtime: ggxchain-node-7 (ggxchain-node-1.tx1.au1)    
2023-08-20 20:29:41 [0] 💸 generated 5 npos voters, 1 from validators and 4 nominators    
2023-08-20 20:29:41 [0] 💸 generated 1 npos targets    
Error: Service(Client(VersionInvalid("cannot deserialize module: UnknownOpcode(192)")))
2023-08-20 20:29:42 Cannot create a runtime error=Other("cannot deserialize module: UnknownOpcode(192)")
```

**Comment by akorchyn** [comment]
As the above issue is confirmed, we can't migrate until the proper fix is created for the substrate. So, let's move to draft it and keep it for latter.

**Comment by xcthulhu** [comment]
Looks like we need to update substrate to incorporate this fix: https://github.com/paritytech/substrate/pull/13804

**Comment by akorchyn** [comment]
it's not easy task as we have other substrate deps. Also, we can live with older version for a while, it's not crucial.

**Comment by uchu** [comment]
I think we need to work on these updates to be able to upgrade rust toolchain

**Comment by akorchyn** [comment]
Absorbed by #187

**Pull request closed without merging**
